### ISSUE TITLE
[python] Why the hatch dependency?

### ISSUE THREAD

**Issue by pamelafox** [microsoft/TypeChat#215]
Will that be always needed? Or is that just for the examples? I've personally never used it nor seen it as a requirement. If its for venv management reasons, we typically use venv since its in standard lib.

**Comment by DanielRosenwasser** [comment]
So I'm not an expert in all the individual tools, but I was looking for something that would manage

* dependencies
* dev-time dependencies
* virtual environments that could deal with both
* editable installs for writing samples/tests that imported the library
* easy packaging/publishing

Since I've gotten my hands dirtier trying to make things work, I've learned enough to do a decent amount of this with just `pip` and `venv`, but solutions like Poetry, Hatch, and Rye made the onramp easier, and still manage a decent amount of it.

Hatch was recommended to me, I think in part because it's being developed by PyPA and tries to align with their recommendations; however, it still feels like it's early days even if the project is promising. I am open to switching to Poetry given the UX, docs, and familiarity that it has, but also open to something more minimal.

**Comment by pamelafox** [comment]
Yes, I recommend showing the pip/venv route, since that is likely to be what developers are expecting to see (and they could adapt for poetry/hatch/etc). I think uisng hatch probably makes particular sense for *contributing* to TypeChat for the dev-time deps, editable install, packaging, but I don't think it makes as much sense as the default path for a *user* of TypeChat.

For example: I got `hatch shell` working in my terminal, but then when I moved to VS Code, I had no idea where the venv got made so I couldn't get VS Code to use the hatch-made venv, and running hatch shell didnt seem to work. I could have read the hatch docs to try to figure it out, but it would have been more straightforward if I had setup via simple venv.
